import { createClient } from "@supabase/supabase-js";
const supabaseUrl = "https://heziklmmhxiollumuqsh.supabase.co"
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlemlrbG1taHhpb2xsdW11cXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjczODQzMzQsImV4cCI6MjA0Mjk2MDMzNH0.wRZ9opeaInQr2Jm5J3dk9IGIO0XqGV4Zf3Sk7uuo82g"
const supabase_project_secret = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlemlrbG1taHhpb2xsdW11cXNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNzM4NDMzNCwiZXhwIjoyMDQyOTYwMzM0fQ.MRFyk3j-vM8fs385Owy3hkOQq_svM58A83gWxha_X40"
